FROM openresty/openresty:xenial
RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http
# RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-lock
RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-auto-ssl